// Sidebar
export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
// Person Data Fields
export const COLLECT_PERSON_DATA = "COLLECT_PERSON_DATA";
// GET Basic Patients
export const GET_BASIC_PATIENTS_ERROR = "GET_BASIC_PATIENTS_ERROR";
export const GET_BASIC_PATIENTS_SUCCESS = "GET_BASIC_PATIENTS_SUCCESS";
export const GET_BASIC_PATIENTS = "GET_BASIC_PATIENT";
// GET Basic Dentists
export const GET_BASIC_DENTISTS_ERROR = "GET_BASIC_DENTISTS_ERROR";
export const GET_BASIC_DENTISTS_SUCCESS = "GET_BASIC_DENTISTS_SUCCESS";
export const GET_BASIC_DENTISTS = "GET_BASIC_DENTISTS";
// GET Complete Patient
export const GET_COMPLETE_PATIENT = "GET_COMPLETE_PATIENT";
export const GET_COMPLETE_PATIENT_ERROR = "GET_COMPLETE_PATIENT_ERROR";
export const GET_COMPLETE_PATIENT_SUCCESS = "GET_COMPLETE_PATIENT_SUCCESS";
// GET Complete Dentist
export const GET_COMPLETE_DENTIST = "GET_COMPLETE_DENTIST";
export const GET_COMPLETE_DENTIST_ERROR = "GET_COMPLETE_DENTIST_ERROR";
export const GET_COMPLETE_DENTIST_SUCCESS = "GET_COMPLETE_DENTIST_SUCCESS";
